### ISSUE TITLE
Evaluating CP model crashes

### ISSUE THREAD

**Issue by JeanKaddour** [facebookresearch/ssl-relation-prediction#13]
Hi Yihong, thank you so much for sharing this awesome repo!!

I tried to run the CP model; training seems to work, but when the validation starts, it crashes:

```
Evaluate the split train
Evaluating the rhs
Traceback (most recent call last):
  File "/home/jean/kg/src/main.py", line 25, in <module>
    main()
  File "/home/jean/kg/src/main.py", line 20, in main
    engine.episode()
  File "/home/jean/kg/src/engines.py", line 329, in episode
    self.validation_step(epoch=epoch, model=self.model)
  File "/home/jean/kg/src/engines.py", line 260, in validation_step
    res_s = self.dataset.eval(
  File "/home/jean/kg/src/datasets.py", line 243, in eval
    metrics = model.get_metric_ogb(
  File "/home/jean/kg/src/models/__init__.py", line 164, in get_metric_ogb
    cands = self.get_candidates(
TypeError: get_candidates() got an unexpected keyword argument 'indices'

```

Maybe the `get_candidates(...)` method of the `CP` class needs to be re-written?

**Comment by yihong-chen** [comment]
Hi Jean, you are right! Currently, I only implemented `get_candidates` (ogb) for the `ComplEx` model. I will be super happy to iterate on `CP`. Is there any timeline you expect for this feature?

**Comment by JeanKaddour** [comment]
Thank you very much! I'm working on a submission due on the 27th and wanted to run one baseline in addition to `ComplEx` until then. No worries if that's too early. Happy to dig deeper into resolving this myself.

**Comment by yihong-chen** [comment]
Hi Jean, I just did a quick patch as follows but only brain-compiled it ;) I guess it should work. Let me know if it doesn't! 

```
  def get_candidates(self, chunk_begin, chunk_size, target='rhs', indices=None):
    if indices == None:
        if target == 'rhs':
            return self.rhs.weight.data[
                chunk_begin:chunk_begin + chunk_size
            ].transpose(0, 1)
        elif target == 'lhs':
            return self.lhs.weight.data[
                chunk_begin:chunk_begin + chunk_size
            ].transpose(0, 1)
        elif target == 'rel':
            return self.rel.weight.data[
                chunk_begin:chunk_begin + chunk_size
            ].transpose(0, 1)
    else:
        assert target != 'rel' # ogb only evaluates entity ranking
        bsz = indices.shape[0]
        num_cands = indices.shape[1]
        if target == 'rhs':
            indices = indices[:, num_cands//2:]
            return self.rhs.weight.data[indices.reshape(-1)].reshape(bsz, num_cands//2, -1)
        else:
            indices = indices[:, 0:num_cands//2]
            return self.lhs.weight.data[indices.reshape(-1)].reshape(bsz, num_cands//2, -1)
```

**Comment by JeanKaddour** [comment]
Thank you so much!! Now it works :)
